export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    COURSES: '/admin/courses',
    COURSE_EDITOR: '/admin/courses/edit/:courseId?',
    COURSE_VIEW: '/admin/courses/view/:courseId',
    ASSIGNMENTS: '/admin/assignments',
    USERS: '/admin/users',
    TESTS: '/admin/tests',
    REWARDS: '/admin/rewards',
    ANALYTICS: '/admin/analytics',
    MEDIA: '/admin/media',
    LOGS: '/admin/logs',
  },
  STUDENT: {
    DASHBOARD: '/student/dashboard',
    COURSES: '/student/courses',
    COURSE_DETAIL: '/student/courses/:id',
    LESSON: '/student/courses/:courseId/lesson/:lessonId',
    TEST: '/student/courses/:courseId/test/:testId',
    PROFILE: '/student/profile',
    REWARDS: '/student/rewards',
    PROGRESS: '/student/progress',
  },
} as const;